import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const products = [
  // Baby Shower - 10 produtos
  { slug: 'baby-shower-bottle-personalized', category: 'baby_shower', name: JSON.stringify({ pt: 'Mamadeira Personalizada', fr: 'Biberon Personnalisé', en: 'Personalized Baby Bottle', de: 'Personalisierte Babyflasche' }), shortDescription: JSON.stringify({ pt: 'Mamadeira com nome gravado', fr: 'Biberon avec nom gravé', en: 'Baby bottle with engraved name', de: 'Babyflasche mit eingraviertem Namen' }), longDescription: JSON.stringify({ pt: 'Mamadeira de vidro resistente com gravação laser personalizada.', fr: 'Biberon en verre résistant avec gravure laser personnalisée.', en: 'Durable glass baby bottle with personalized laser engraving.', de: 'Robuste Glasflasche mit personalisierter Lasergravur.' }), priceCents: 2800, stock: 15, featured: true },
  { slug: 'baby-shower-pacifier-holder', category: 'baby_shower', name: JSON.stringify({ pt: 'Corrente de Chupeta', fr: 'Chaîne de Sucette', en: 'Pacifier Holder Chain', de: 'Schnullerkette' }), shortDescription: JSON.stringify({ pt: 'Corrente com nome gravado', fr: 'Chaîne avec nom gravé', en: 'Chain with engraved name', de: 'Kette mit eingraviertem Namen' }), longDescription: JSON.stringify({ pt: 'Corrente de madeira e acrílico com gravação personalizada.', fr: 'Chaîne en bois et acrylique avec gravure personnalisée.', en: 'Wooden and acrylic chain with personalized engraving.', de: 'Kette aus Holz und Acryl mit personalisierter Gravur.' }), priceCents: 1500, stock: 25 },
  { slug: 'baby-shower-onesie-print', category: 'baby_shower', name: JSON.stringify({ pt: 'Body Personalizado', fr: 'Body Personnalisé', en: 'Personalized Onesie', de: 'Personalisierter Body' }), shortDescription: JSON.stringify({ pt: 'Body de bebé com sublimação personalizada', fr: 'Body bébé avec sublimation personnalisée', en: 'Baby onesie with custom sublimation', de: 'Baby-Body mit benutzerdefinierter Sublimation' }), longDescription: JSON.stringify({ pt: 'Body 100% algodão com impressão UV personalizada.', fr: 'Body 100% coton com impression UV personnalisée.', en: '100% cotton onesie with custom UV printing.', de: '100% Baumwoll-Body mit benutzerdefiniertem UV-Druck.' }), priceCents: 1800, stock: 20, featured: true },
  { slug: 'baby-shower-name-plaque', category: 'baby_shower', name: JSON.stringify({ pt: 'Placa com Nome', fr: 'Plaque avec Nom', en: 'Name Plaque', de: 'Namensplakette' }), shortDescription: JSON.stringify({ pt: 'Placa de madeira para quarto', fr: 'Plaque en bois pour chambre', en: 'Wooden wall plaque', de: 'Holzwandplakette' }), longDescription: JSON.stringify({ pt: 'Placa de madeira MDF gravada a laser com o nome do bebé.', fr: 'Plaque en bois MDF gravée au laser avec le nom du bébé.', en: 'Laser-engraved MDF wood plaque with baby\'s name.', de: 'Laser-gravierte MDF-Holzplakette mit Babynamen.' }), priceCents: 2200, stock: 18 },
  { slug: 'baby-shower-milestone-cards', category: 'baby_shower', name: JSON.stringify({ pt: 'Cartões de Marcos', fr: 'Cartes Jalons', en: 'Milestone Cards', de: 'Meilenstein-Karten' }), shortDescription: JSON.stringify({ pt: 'Kit de 12 cartões impressos', fr: 'Kit de 12 cartes imprimées', en: 'Set of 12 printed cards', de: 'Satz von 12 bedruckten Karten' }), longDescription: JSON.stringify({ pt: 'Kit com 12 cartões marcos para fotos do bebé.', fr: 'Kit avec 12 cartes jalons pour photos bébé.', en: 'Kit with 12 milestone cards for baby photos.', de: 'Kit mit 12 Meilenstein-Karten für Babyfotos.' }), priceCents: 1900, stock: 22 },
  { slug: 'baby-shower-rattle-3d-print', category: 'baby_shower', name: JSON.stringify({ pt: 'Chocalho 3D', fr: 'Hochet 3D', en: '3D Printed Rattle', de: '3D gedrucktes Rasseln' }), shortDescription: JSON.stringify({ pt: 'Chocalho impresso em 3D colorido', fr: 'Hochet imprimé en 3D coloré', en: 'Colorful 3D printed rattle', de: 'Buntes 3D-gedrucktes Rasseln' }), longDescription: JSON.stringify({ pt: 'Chocalho seguro para bebés, impresso em 3D.', fr: 'Hochet sûr pour bébés, imprimé en 3D.', en: 'Safe baby rattle, 3D printed with non-toxic filament.', de: 'Sicheres Babyrasseln, 3D-gedruckt.' }), priceCents: 2500, stock: 12 },
  { slug: 'baby-shower-photo-frame', category: 'baby_shower', name: JSON.stringify({ pt: 'Moldura com Foto', fr: 'Cadre Photo Personnalisé', en: 'Personalized Photo Frame', de: 'Personalisierter Bilderrahmen' }), shortDescription: JSON.stringify({ pt: 'Moldura de madeira com foto gravada', fr: 'Cadre en bois avec photo gravée', en: 'Wooden frame with engraved photo', de: 'Holzrahmen mit graviertem Foto' }), longDescription: JSON.stringify({ pt: 'Moldura de madeira com gravação laser de foto personalizada.', fr: 'Cadre en bois avec gravure laser de photo personnalisée.', en: 'Wooden frame with personalized laser-engraved photo.', de: 'Holzrahmen mit personalisiertem Laser-Fotogravur.' }), priceCents: 3200, stock: 10, featured: true },
  { slug: 'baby-shower-bib-set', category: 'baby_shower', name: JSON.stringify({ pt: 'Kit de Babadores', fr: 'Ensemble de Bavoirs', en: 'Bib Set', de: 'Lätzchensatz' }), shortDescription: JSON.stringify({ pt: 'Kit com 3 babadores personalizados', fr: 'Ensemble de 3 bavoirs personnalisés', en: 'Set of 3 personalized bibs', de: 'Satz von 3 personalisierten Lätzchen' }), longDescription: JSON.stringify({ pt: 'Kit com 3 babadores de algodão com sublimação personalizada.', fr: 'Ensemble de 3 bavoirs en coton avec sublimation personnalisée.', en: 'Set of 3 cotton bibs with custom sublimation.', de: 'Satz von 3 Baumwolllätzchen mit benutzerdefinierter Sublimation.' }), priceCents: 2100, stock: 14 },
  { slug: 'baby-shower-crib-banner', category: 'baby_shower', name: JSON.stringify({ pt: 'Faixa para Berço', fr: 'Bannière de Berceau', en: 'Crib Banner', de: 'Wiege Banner' }), shortDescription: JSON.stringify({ pt: 'Faixa de pano com nome', fr: 'Bannière en tissu avec nom', en: 'Fabric banner with name', de: 'Stoffbanner mit Namen' }), longDescription: JSON.stringify({ pt: 'Faixa de pano impresso com o nome do bebé.', fr: 'Bannière en tissu imprimée avec le nom du bébé.', en: 'Printed fabric banner with baby\'s name.', de: 'Bedrucktes Stoffbanner mit Babynamen.' }), priceCents: 1600, stock: 16 },
  { slug: 'baby-shower-growth-chart', category: 'baby_shower', name: JSON.stringify({ pt: 'Medidor de Crescimento', fr: 'Règle de Croissance', en: 'Growth Chart', de: 'Wachstumsmesser' }), shortDescription: JSON.stringify({ pt: 'Medidor personalizado para parede', fr: 'Règle personnalisée pour mur', en: 'Personalized wall growth chart', de: 'Personalisierter Wand-Wachstumsmesser' }), longDescription: JSON.stringify({ pt: 'Medidor de madeira com gravação laser e nome personalizado.', fr: 'Règle en bois avec gravure laser et nom personnalisé.', en: 'Wooden growth chart with laser engraving and personalized name.', de: 'Holz-Wachstumsmesser mit Lasergravur und personalisiertem Namen.' }), priceCents: 2800, stock: 11 },
  { slug: 'corporate-gift-box-custom', category: 'corporate', name: JSON.stringify({ pt: 'Caixa de Presentes Corporativa', fr: 'Boîte Cadeau Corporative', en: 'Corporate Gift Box', de: 'Unternehmensgeschenkbox' }), shortDescription: JSON.stringify({ pt: 'Caixa personalizada com logo', fr: 'Boîte personnalisée avec logo', en: 'Box with personalized logo', de: 'Box mit personalisiertem Logo' }), longDescription: JSON.stringify({ pt: 'Caixa MDF gravada a laser com logo da empresa.', fr: 'Boîte MDF gravée au laser avec logo de l\'entreprise.', en: 'Laser-engraved MDF box with company logo.', de: 'Laser-gravierte MDF-Box mit Unternehmenslogo.' }), priceCents: 4500, stock: 8, featured: true },
  { slug: 'corporate-pen-holder-3d', category: 'corporate', name: JSON.stringify({ pt: 'Suporte para Canetas 3D', fr: 'Porte-stylos 3D', en: '3D Pen Holder', de: '3D Stifthalter' }), shortDescription: JSON.stringify({ pt: 'Suporte impresso em 3D personalizado', fr: 'Porte-stylos imprimé en 3D personnalisé', en: 'Custom 3D printed pen holder', de: 'Benutzerdefinierter 3D-gedruckter Stifthalter' }), longDescription: JSON.stringify({ pt: 'Suporte para canetas impresso em 3D com nome da empresa.', fr: 'Porte-stylos imprimé em 3D avec le nom de l\'entreprise.', en: 'Pen holder 3D printed with company name or logo.', de: 'Stifthalter 3D-gedruckt mit Unternehmensname oder Logo.' }), priceCents: 3200, stock: 15, featured: true },
  { slug: 'corporate-nameplate-acrylic', category: 'corporate', name: JSON.stringify({ pt: 'Placa de Acrílico para Secretária', fr: 'Plaque Acrylique de Bureau', en: 'Acrylic Desk Nameplate', de: 'Acryl-Büroschild' }), shortDescription: JSON.stringify({ pt: 'Placa de acrílico gravada a laser', fr: 'Plaque acrylique gravée au laser', en: 'Laser-engraved acrylic plaque', de: 'Laser-gravierte Acrylplakette' }), longDescription: JSON.stringify({ pt: 'Placa de acrílico com gravação laser de nome e cargo.', fr: 'Plaque acrylique avec gravure laser du nom et du titre.', en: 'Acrylic plaque with laser-engraved name and title.', de: 'Acrylplakette mit laser-graviertem Namen und Titel.' }), priceCents: 2800, stock: 12 },
  { slug: 'corporate-mug-print', category: 'corporate', name: JSON.stringify({ pt: 'Caneca Personalizada', fr: 'Mug Personnalisé', en: 'Personalized Mug', de: 'Personalisierte Tasse' }), shortDescription: JSON.stringify({ pt: 'Caneca com sublimação personalizada', fr: 'Mug avec sublimation personnalisée', en: 'Mug with custom sublimation', de: 'Tasse mit benutzerdefinierter Sublimation' }), longDescription: JSON.stringify({ pt: 'Caneca de cerâmica com impressão UV e logo corporativo.', fr: 'Mug en céramique avec impression UV et logo corporate.', en: 'Ceramic mug with UV printing and corporate logo.', de: 'Keramiktasse mit UV-Druck und Unternehmenslogo.' }), priceCents: 1500, stock: 30 },
  { slug: 'corporate-award-trophy', category: 'corporate', name: JSON.stringify({ pt: 'Troféu Corporativo', fr: 'Trophée Corporatif', en: 'Corporate Trophy', de: 'Unternehmenspokal' }), shortDescription: JSON.stringify({ pt: 'Troféu personalizado com placa', fr: 'Trophée personnalisé avec plaque', en: 'Trophy with custom nameplate', de: 'Pokal mit personalisiertem Schild' }), longDescription: JSON.stringify({ pt: 'Troféu de acrílico e madeira com placa de gravação personalizada.', fr: 'Trophée en acrylique et bois avec plaque de gravure personnalisée.', en: 'Acrylic and wood trophy with custom engraved nameplate.', de: 'Acryl- und Holzpokal mit personalisiertem Gravurschild.' }), priceCents: 5500, stock: 6 },
  { slug: 'corporate-desk-calendar', category: 'corporate', name: JSON.stringify({ pt: 'Calendário de Secretária', fr: 'Calendrier de Bureau', en: 'Desk Calendar', de: 'Bürokalender' }), shortDescription: JSON.stringify({ pt: 'Calendário com logo personalizado', fr: 'Calendrier avec logo personnalisé', en: 'Calendar with custom logo', de: 'Kalender mit personalisiertem Logo' }), longDescription: JSON.stringify({ pt: 'Calendário de madeira gravado a laser com logo e datas.', fr: 'Calendrier en bois gravé au laser avec logo et dates.', en: 'Laser-engraved wooden calendar with company logo and dates.', de: 'Laser-gravierter Holzkalender mit Unternehmenslogo und -daten.' }), priceCents: 2200, stock: 10 },
  { slug: 'corporate-leather-coaster', category: 'corporate', name: JSON.stringify({ pt: 'Suportes de Couro', fr: 'Sous-verres en Cuir', en: 'Leather Coasters', de: 'Leder-Untersetzer' }), shortDescription: JSON.stringify({ pt: 'Kit com 4 suportes de couro gravados', fr: 'Kit avec 4 sous-verres en cuir gravés', en: 'Set of 4 engraved leather coasters', de: 'Satz von 4 gravierten Leder-Untersetzern' }), longDescription: JSON.stringify({ pt: 'Kit com 4 suportes de couro genuíno com gravação personalizada.', fr: 'Kit avec 4 sous-verres en cuir véritable avec gravure personnalisée.', en: 'Set of 4 genuine leather coasters with personalized engraving.', de: 'Satz von 4 Untersetzern aus echtem Leder mit personalisierter Gravur.' }), priceCents: 3500, stock: 8 },
  { slug: 'corporate-business-card-holder', category: 'corporate', name: JSON.stringify({ pt: 'Suporte para Cartões', fr: 'Porte-cartes Professionnel', en: 'Business Card Holder', de: 'Visitenkarten-Halter' }), shortDescription: JSON.stringify({ pt: 'Suporte de madeira gravado', fr: 'Porte-cartes en bois gravé', en: 'Engraved wooden card holder', de: 'Gravierter Holz-Kartenhalter' }), longDescription: JSON.stringify({ pt: 'Suporte para cartões de visita em madeira com gravação personalizada.', fr: 'Porte-cartes de visite en bois avec gravure personnalisée.', en: 'Wooden business card holder with personalized logo engraving.', de: 'Holz-Visitenkarten-Halter mit personalisierter Logo-Gravur.' }), priceCents: 1800, stock: 14 },
  { slug: 'corporate-keychain-metal', category: 'corporate', name: JSON.stringify({ pt: 'Chaveiros Personalizados', fr: 'Porte-clés Personnalisés', en: 'Personalized Keychains', de: 'Personalisierte Schlüsselanhänger' }), shortDescription: JSON.stringify({ pt: 'Chaveiros de metal com logo', fr: 'Porte-clés en métal com logo', en: 'Metal keychains with logo', de: 'Metallschlüsselanhänger mit Logo' }), longDescription: JSON.stringify({ pt: 'Chaveiros de metal personalizados com gravação do logo corporativo.', fr: 'Porte-clés en métal personnalisés com gravure du logo corporate.', en: 'Personalized metal keychains with engraved company logo.', de: 'Personalisierte Metallschlüsselanhänger mit graviertem Unternehmenslogo.' }), priceCents: 1200, stock: 50, featured: true },
  { slug: 'wedding-invitation-custom', category: 'wedding', name: JSON.stringify({ pt: 'Convite Personalizado', fr: 'Invitation Personnalisée', en: 'Custom Wedding Invitation', de: 'Personalisierte Hochzeitseinladung' }), shortDescription: JSON.stringify({ pt: 'Convite gravado a laser', fr: 'Invitation gravée au laser', en: 'Laser-engraved invitation', de: 'Laser-gravierte Einladung' }), longDescription: JSON.stringify({ pt: 'Convite de casamento em papel premium com gravação laser personalizada.', fr: 'Invitation de mariage sur papier de haute qualité com gravure laser personnalisée.', en: 'Wedding invitation on premium paper with personalized laser engraving.', de: 'Hochzeitseinladung auf hochwertigem Papier mit personalisierter Lasergravur.' }), priceCents: 3500, stock: 10, featured: true },
  { slug: 'wedding-place-card-name', category: 'wedding', name: JSON.stringify({ pt: 'Cartão de Lugar', fr: 'Carte de Place', en: 'Place Card', de: 'Tischkarte' }), shortDescription: JSON.stringify({ pt: 'Cartão gravado com nome', fr: 'Carte gravée com nom', en: 'Card with guest name', de: 'Karte mit Gastname' }), longDescription: JSON.stringify({ pt: 'Cartões de lugar em papel premium com gravação personalizada de nomes.', fr: 'Cartes de place sur papier premium com gravure personnalisée du nome dos invités.', en: 'Premium paper place cards with personalized guest name engraving.', de: 'Premium-Papier-Tischkarten mit personalisierter Gastnamengravur.' }), priceCents: 2800, stock: 25 },
  { slug: 'wedding-ring-box-3d', category: 'wedding', name: JSON.stringify({ pt: 'Caixa para Alianças', fr: 'Boîte pour Alliances', en: 'Ring Box', de: 'Ringbox' }), shortDescription: JSON.stringify({ pt: 'Caixa 3D personalizada', fr: 'Boîte 3D personnalisée', en: 'Custom 3D ring box', de: 'Benutzerdefinierte 3D-Ringbox' }), longDescription: JSON.stringify({ pt: 'Caixa para alianças impressa em 3D com nomes dos noivos gravados.', fr: 'Boîte pour alliances imprimée en 3D com nomes dos mariés gravés.', en: '3D printed ring box with engraved names of the bride and groom.', de: '3D-gedruckte Ringbox mit gravierten Namen des Brautpaares.' }), priceCents: 4200, stock: 8, featured: true },
  { slug: 'wedding-cake-topper', category: 'wedding', name: JSON.stringify({ pt: 'Topo de Bolo', fr: 'Décoration Gâteau', en: 'Cake Topper', de: 'Tortendekoration' }), shortDescription: JSON.stringify({ pt: 'Topo 3D gravado com nomes', fr: 'Décoration 3D gravée com noms', en: '3D topper with names', de: '3D-Dekoration mit Namen' }), longDescription: JSON.stringify({ pt: 'Topo de bolo impresso em 3D ou madeira com nomes do casal.', fr: 'Décoration gâteau imprimée em 3D ou bois com les nomes do couple.', en: 'Cake topper 3D printed or wooden with couple\'s names.', de: 'Tortendekoration 3D-gedruckt oder Holz mit dem Namen des Paares.' }), priceCents: 3200, stock: 12 },
  { slug: 'wedding-guest-book-custom', category: 'wedding', name: JSON.stringify({ pt: 'Livro de Visitas', fr: 'Livre d\'Or', en: 'Guest Book', de: 'Gästebuch' }), shortDescription: JSON.stringify({ pt: 'Livro gravado com nomes', fr: 'Livre gravé com noms', en: 'Book with engraved names', de: 'Buch mit gravierten Namen' }), longDescription: JSON.stringify({ pt: 'Livro de visitas com capa de madeira gravada e papel interior premium.', fr: 'Livre d\'or com couverture em bois gravée et papier intérieur premium.', en: 'Guest book with engraved wooden cover and premium interior paper.', de: 'Gästebuch mit graviertem Holzcover und hochwertigem Innenpapier.' }), priceCents: 5500, stock: 6 },
  { slug: 'wedding-thank-you-card', category: 'wedding', name: JSON.stringify({ pt: 'Cartão de Agradecimento', fr: 'Carte de Remerciement', en: 'Thank You Card', de: 'Danksagungskarte' }), shortDescription: JSON.stringify({ pt: 'Cartões impressos personalizados', fr: 'Cartes imprimées personnalisées', en: 'Custom printed cards', de: 'Benutzerdefinierte gedruckte Karten' }), longDescription: JSON.stringify({ pt: 'Cartões de agradecimento impressos com design personalizado e nomes.', fr: 'Cartes de remerciement imprimées com design personnalisé et nomes dos mariés.', en: 'Thank you cards printed with custom design and couple\'s names.', de: 'Dankesagungskarten mit benutzerdefiniertem Design und Namen des Paares bedruckt.' }), priceCents: 2200, stock: 40 },
  { slug: 'wedding-table-number', category: 'wedding', name: JSON.stringify({ pt: 'Números de Mesa', fr: 'Numéros de Table', en: 'Table Numbers', de: 'Tischnummern' }), shortDescription: JSON.stringify({ pt: 'Números gravados em madeira', fr: 'Numéros gravés en bois', en: 'Engraved wood numbers', de: 'Gravierte Holznummern' }), longDescription: JSON.stringify({ pt: 'Números de mesa em madeira ou acrílico gravados a laser.', fr: 'Numéros de table en bois ou acrylique gravés au laser.', en: 'Table numbers in wood or acrylic laser-engraved.', de: 'Tischnummern aus Holz oder Acryl laser-graviert.' }), priceCents: 1800, stock: 20 },
  { slug: 'wedding-seating-chart', category: 'wedding', name: JSON.stringify({ pt: 'Plano de Mesas', fr: 'Plan de Placement', en: 'Seating Chart', de: 'Sitzplan' }), shortDescription: JSON.stringify({ pt: 'Painel gravado personalizado', fr: 'Panneau gravé personnalisé', en: 'Custom engraved panel', de: 'Benutzerdefiniertes graviertes Panel' }), longDescription: JSON.stringify({ pt: 'Painel grande de madeira com gravação do plano de mesas.', fr: 'Grand panneau en bois com gravure du plan de placement.', en: 'Large wooden panel with engraved seating chart.', de: 'Großes Holz-Panel mit graviertem Sitzplan.' }), priceCents: 6500, stock: 4, featured: true },
  { slug: 'wedding-favor-box', category: 'wedding', name: JSON.stringify({ pt: 'Caixa de Favor', fr: 'Boîte Cadeau Mariage', en: 'Favor Box', de: 'Geschenkbox' }), shortDescription: JSON.stringify({ pt: 'Caixa MDF para brinde', fr: 'Boîte MDF pour brinde', en: 'MDF favor box', de: 'MDF-Geschenkbox' }), longDescription: JSON.stringify({ pt: 'Caixa MDF gravada com nomes dos noivos para lembrança de casamento.', fr: 'Boîte MDF gravée com nomes dos mariés para souvenir de mariage.', en: 'Laser-engraved MDF favor box with couple\'s names for wedding memories.', de: 'Laser-gravierte MDF-Geschenkbox mit dem Namen des Paares für Hochzeitserinnerungen.' }), priceCents: 2800, stock: 30 },
  { slug: 'baptism-invitation-card', category: 'baptism', name: JSON.stringify({ pt: 'Convite de Batizado', fr: 'Invitation Baptême', en: 'Baptism Invitation', de: 'Taufeinladung' }), shortDescription: JSON.stringify({ pt: 'Convite gravado personalizado', fr: 'Invitation gravée personnalisée', en: 'Personalized engraved invitation', de: 'Personalisierte Gravureinladung' }), longDescription: JSON.stringify({ pt: 'Convite de batizado em papel premium com gravação personalizada.', fr: 'Invitation de baptême sur papier premium com gravure personnalisée.', en: 'Baptism invitation on premium paper with personalized engraving.', de: 'Taufeinladung auf hochwertigem Papier mit personalisierter Gravur.' }), priceCents: 3200, stock: 15, featured: true },
  { slug: 'baptism-cross-pendant', category: 'baptism', name: JSON.stringify({ pt: 'Cruz Pendente 3D', fr: 'Croix Pendentif 3D', en: '3D Cross Pendant', de: '3D Kreuzanhänger' }), shortDescription: JSON.stringify({ pt: 'Cruz impressa em 3D personalizada', fr: 'Croix imprimée en 3D personnalisée', en: 'Custom 3D printed cross', de: 'Benutzerdefinierter 3D-gedruckter Kreuz' }), longDescription: JSON.stringify({ pt: 'Cruz pendente impressa em 3D com nome do batizado.', fr: 'Croix pendentif imprimée en 3D com le nome do baptisé.', en: '3D printed cross pendant with child\'s name.', de: '3D-gedruckter Kreuzanhänger mit dem Namen des Taufkindes.' }), priceCents: 2800, stock: 10 },
  { slug: 'baptism-candle-personalized', category: 'baptism', name: JSON.stringify({ pt: 'Vela de Batizado', fr: 'Bougie Baptême', en: 'Baptism Candle', de: 'Taufkerze' }), shortDescription: JSON.stringify({ pt: 'Vela com gravação personalizada', fr: 'Bougie com gravure personnalisée', en: 'Candle with custom engraving', de: 'Kerze mit benutzerdefinierter Gravur' }), longDescription: JSON.stringify({ pt: 'Vela de parafina com gravação laser do nome e data do batizado.', fr: 'Bougie em paraffine com gravure laser du nome e date do baptême.', en: 'Paraffin candle with laser-engraved name and baptism date.', de: 'Paraffinkerze mit laser-graviertem Namen und Taufdatum.' }), priceCents: 1500, stock: 20 },
  { slug: 'baptism-frame-photo', category: 'baptism', name: JSON.stringify({ pt: 'Moldura para Foto', fr: 'Cadre Photo', en: 'Photo Frame', de: 'Bilderrahmen' }), shortDescription: JSON.stringify({ pt: 'Moldura gravada com nome', fr: 'Cadre gravé com nom', en: 'Frame with engraved name', de: 'Rahmen mit graviertem Namen' }), longDescription: JSON.stringify({ pt: 'Moldura de madeira com gravação do nome para foto do batizado.', fr: 'Cadre en bois com gravure du nome para foto do baptême.', en: 'Wooden frame with engraved name for baptism photo.', de: 'Holzrahmen mit graviertem Namen für Tautfoto.' }), priceCents: 2500, stock: 12 },
  { slug: 'baptism-guest-book', category: 'baptism', name: JSON.stringify({ pt: 'Livro de Presença', fr: 'Livre de Présence', en: 'Guest Book', de: 'Gästebuch' }), shortDescription: JSON.stringify({ pt: 'Livro com capa gravada', fr: 'Livre com couverture gravée', en: 'Book with engraved cover', de: 'Buch mit graviertem Umschlag' }), longDescription: JSON.stringify({ pt: 'Livro de presença com capa de madeira gravada com nome e data.', fr: 'Livre de présence avec couverture em bois gravée com nom e date.', en: 'Guest book with wooden cover engraved with name and date.', de: 'Anwesenheitsbuch mit Holzcover graviert mit Namen und Datum.' }), priceCents: 4200, stock: 8 },
  { slug: 'baptism-medal-custom', category: 'baptism', name: JSON.stringify({ pt: 'Medalha Personalizada', fr: 'Médaille Personnalisée', en: 'Custom Medal', de: 'Personalisierte Medaille' }), shortDescription: JSON.stringify({ pt: 'Medalha de metal com gravação', fr: 'Médaille en métal com gravure', en: 'Metal medal with engraving', de: 'Metallmedaille mit Gravur' }), longDescription: JSON.stringify({ pt: 'Medalha de metal com fita personalizada e gravação do nome.', fr: 'Médaille en métal com ruban personnalisé e gravure do nome.', en: 'Metal medal with personalized ribbon and engraved name.', de: 'Metallmedaille mit personalisiertem Band und graviertem Namen.' }), priceCents: 2200, stock: 14 },
  { slug: 'baptism-favor-bag', category: 'baptism', name: JSON.stringify({ pt: 'Saco de Favor', fr: 'Sac Cadeau', en: 'Favor Bag', de: 'Geschenktasche' }), shortDescription: JSON.stringify({ pt: 'Saco com impressão personalizada', fr: 'Sac com impression personnalisée', en: 'Bag with custom printing', de: 'Tasche mit benutzerdefiniertem Druck' }), longDescription: JSON.stringify({ pt: 'Saco de papel ou tecido impresso com nome e data do batizado.', fr: 'Sac em papier ou tissu imprimé com nome e date do baptême.', en: 'Paper or fabric bag printed with name and baptism date.', de: 'Papier- oder Stofftasche mit Namen und Taufdatum bedruckt.' }), priceCents: 1800, stock: 25 },
  { slug: 'baptism-bible-cover', category: 'baptism', name: JSON.stringify({ pt: 'Capa de Bíblia', fr: 'Couverture Bible', en: 'Bible Cover', de: 'Bibelumschlag' }), shortDescription: JSON.stringify({ pt: 'Capa de couro gravada', fr: 'Couverture en cuir gravée', en: 'Engraved leather cover', de: 'Gravierter Lederumschlag' }), longDescription: JSON.stringify({ pt: 'Capa de bíblia em couro com gravação personalizada do nome.', fr: 'Couverture de bible em couro com gravure personnalisée do nome.', en: 'Leather bible cover with personalized name engraving.', de: 'Leder-Bibelumschlag mit personalisierter Namengravur.' }), priceCents: 3500, stock: 7 },
  { slug: 'baptism-plaque-wall', category: 'baptism', name: JSON.stringify({ pt: 'Placa de Parede', fr: 'Plaque Murale', en: 'Wall Plaque', de: 'Wandplakette' }), shortDescription: JSON.stringify({ pt: 'Placa gravada para quarto', fr: 'Plaque gravée pour chambre', en: 'Plaque for bedroom', de: 'Plakette für Schlafzimmer' }), longDescription: JSON.stringify({ pt: 'Placa de madeira com gravação do nome e data do batizado.', fr: 'Plaque en bois com gravure do nome e date do baptême.', en: 'Wooden plaque with engraved name and baptism date.', de: 'Holzplakette mit graviertem Namen und Taufdatum.' }), priceCents: 2800, stock: 10, featured: true },
  { slug: 'birthday-invitation-custom', category: 'birthday', name: JSON.stringify({ pt: 'Convite de Aniversário', fr: 'Invitation Anniversaire', en: 'Birthday Invitation', de: 'Geburtstagseinladung' }), shortDescription: JSON.stringify({ pt: 'Convite personalizado gravado', fr: 'Invitation personnalisée gravée', en: 'Personalized engraved invitation', de: 'Personalisierte gravierte Einladung' }), longDescription: JSON.stringify({ pt: 'Convite de aniversário em papel premium com gravação personalizada.', fr: 'Invitation d\'anniversaire sur papier premium com gravure personnalisée.', en: 'Birthday invitation on premium paper with personalized engraving.', de: 'Geburtstagseinladung auf hochwertigem Papier mit personalisierter Gravur.' }), priceCents: 2800, stock: 20, featured: true },
  { slug: 'birthday-banner-personalized', category: 'birthday', name: JSON.stringify({ pt: 'Faixa de Aniversário', fr: 'Bannière Anniversaire', en: 'Birthday Banner', de: 'Geburtstagsbanner' }), shortDescription: JSON.stringify({ pt: 'Faixa impressa personalizada', fr: 'Bannière imprimée personnalisée', en: 'Custom printed banner', de: 'Benutzerdefiniertes gedrucktes Banner' }), longDescription: JSON.stringify({ pt: 'Faixa de pano impresso com nome e data de aniversário.', fr: 'Bannière em tissu imprimé com nome e date d\'anniversaire.', en: 'Printed fabric banner with name and birthday date.', de: 'Bedrucktes Stoffbanner mit Namen und Geburtstagsdatum.' }), priceCents: 1600, stock: 18 },
  { slug: 'birthday-cake-topper-name', category: 'birthday', name: JSON.stringify({ pt: 'Topo de Bolo com Nome', fr: 'Décoration Gâteau Nom', en: 'Cake Topper with Name', de: 'Tortendekoration mit Namen' }), shortDescription: JSON.stringify({ pt: 'Topo 3D ou gravado', fr: 'Décoration 3D ou gravée', en: '3D or engraved topper', de: '3D oder gravierte Dekoration' }), longDescription: JSON.stringify({ pt: 'Topo de bolo impresso em 3D ou em madeira com o nome personalizado.', fr: 'Décoration gâteau imprimée em 3D ou em bois com le nome personnalisé.', en: '3D printed or wooden cake topper with personalized name.', de: '3D-gedruckte oder Holz-Tortendekoration mit personalisiertem Namen.' }), priceCents: 2500, stock: 15 },
  { slug: 'birthday-party-gift-bag', category: 'birthday', name: JSON.stringify({ pt: 'Saco de Presentes', fr: 'Sac Cadeau Fête', en: 'Party Gift Bag', de: 'Party-Geschenktasche' }), shortDescription: JSON.stringify({ pt: 'Saco impresso personalizado', fr: 'Sac imprimé personnalisé', en: 'Custom printed bag', de: 'Benutzerdefinierte gedruckte Tasche' }), longDescription: JSON.stringify({ pt: 'Saco de papel impresso com nome da criança e motivos de festa.', fr: 'Sac em papier imprimé com le nome de l\'enfant et motifs de fête.', en: 'Paper bag printed with child\'s name and party designs.', de: 'Papiertasche mit dem Namen des Kindes und Partymotiven bedruckt.' }), priceCents: 1500, stock: 30 },
  { slug: 'birthday-thank-you-card', category: 'birthday', name: JSON.stringify({ pt: 'Cartão de Agradecimento', fr: 'Carte de Remerciement', en: 'Thank You Card', de: 'Danksagungskarte' }), shortDescription: JSON.stringify({ pt: 'Cartões impressos personalizados', fr: 'Cartes imprimées personnalisées', en: 'Custom printed cards', de: 'Benutzerdefinierte gedruckte Karten' }), longDescription: JSON.stringify({ pt: 'Cartões de agradecimento impressos com design personalizado.', fr: 'Cartes de remerciement imprimées com design personnalisé.', en: 'Thank you cards printed with custom design for guests.', de: 'Dankesagungskarten mit benutzerdefiniertem Design bedruckt.' }), priceCents: 1800, stock: 35 },
  { slug: 'birthday-milestone-board', category: 'birthday', name: JSON.stringify({ pt: 'Placa de Marcos', fr: 'Plaque Étapes', en: 'Milestone Board', de: 'Meilenstein-Tafel' }), shortDescription: JSON.stringify({ pt: 'Placa gravada para fotos', fr: 'Plaque gravée pour photos', en: 'Engraved photo plaque', de: 'Gravierte Foto-Plakette' }), longDescription: JSON.stringify({ pt: 'Placa de madeira gravada com marcos de idade para fotos da festa.', fr: 'Plaque en bois gravée com étapes d\'âge pour photos de fête.', en: 'Wooden plaque engraved with age milestones for party photos.', de: 'Holzplakette graviert mit Altersmeilensteinen für Partyfotos.' }), priceCents: 2200, stock: 12 },
  { slug: 'birthday-personalized-mug', category: 'birthday', name: JSON.stringify({ pt: 'Caneca Personalizada', fr: 'Mug Personnalisé', en: 'Personalized Mug', de: 'Personalisierte Tasse' }), shortDescription: JSON.stringify({ pt: 'Caneca com foto e nome', fr: 'Mug com photo et nome', en: 'Mug with photo and name', de: 'Tasse mit Foto und Namen' }), longDescription: JSON.stringify({ pt: 'Caneca de cerâmica com impressão UV de foto e nome personalizado.', fr: 'Mug em céramique com impression UV de photo et nome personnalisé.', en: 'Ceramic mug with UV-printed photo and personalized name.', de: 'Keramiktasse mit UV-gedrucktem Foto und personalisiertem Namen.' }), priceCents: 1500, stock: 20, featured: true },
  { slug: 'birthday-t-shirt-print', category: 'birthday', name: JSON.stringify({ pt: 'T-Shirt Personalizada', fr: 'T-Shirt Personnalisé', en: 'Personalized T-Shirt', de: 'Personalisiertes T-Shirt' }), shortDescription: JSON.stringify({ pt: 'T-shirt com sublimação', fr: 'T-shirt com sublimation', en: 'T-shirt with sublimation', de: 'T-Shirt mit Sublimation' }), longDescription: JSON.stringify({ pt: 'T-shirt 100% algodão com impressão UV personalizada com nome.', fr: 'T-shirt 100% coton com impression UV personnalisée com nome.', en: '100% cotton t-shirt with custom UV printing with name.', de: '100% Baumwoll-T-Shirt mit benutzerdefiniertem UV-Druck mit Namen.' }), priceCents: 1800, stock: 16 },
  { slug: 'birthday-keepsake-box', category: 'birthday', name: JSON.stringify({ pt: 'Caixa de Recordações', fr: 'Boîte Souvenir', en: 'Keepsake Box', de: 'Erinnerungsbox' }), shortDescription: JSON.stringify({ pt: 'Caixa de madeira gravada', fr: 'Boîte em bois gravée', en: 'Engraved wooden box', de: 'Gravierte Holzbox' }), longDescription: JSON.stringify({ pt: 'Caixa de madeira gravada com nome e data de aniversário.', fr: 'Boîte em bois gravée com nome e date d\'anniversário.', en: 'Wooden box engraved with name and birthday date to keep memories.', de: 'Holzbox graviert mit Namen und Geburtstagsdatum zum Aufbewahren.' }), priceCents: 3200, stock: 9 },
  { slug: 'travel-souvenir-personalized-plate', category: 'travel_souvenirs', name: JSON.stringify({ pt: 'Prato de Lembrança', fr: 'Assiette Souvenir', en: 'Souvenir Plate', de: 'Souvenirteller' }), shortDescription: JSON.stringify({ pt: 'Prato com foto e nome de destino', fr: 'Assiette com photo et nom de destination', en: 'Plate with destination photo', de: 'Teller mit Zielortfoto' }), longDescription: JSON.stringify({ pt: 'Prato de cerâmica com sublimação de foto de viagem e nome de local.', fr: 'Assiette em céramique com sublimation de photo de voyage et nom du lieu.', en: 'Ceramic plate with sublimation of travel photo and destination name.', de: 'Keramikteller mit Sublimation von Reisefoto und Zielnamen.' }), priceCents: 2200, stock: 12, featured: true },
  { slug: 'travel-souvenir-magnet-custom', category: 'travel_souvenirs', name: JSON.stringify({ pt: 'Íman Personalizado', fr: 'Aimant Personnalisé', en: 'Custom Magnet', de: 'Benutzerdefinierter Magnet' }), shortDescription: JSON.stringify({ pt: 'Íman com foto da viagem', fr: 'Aimant com photo du voyage', en: 'Magnet with travel photo', de: 'Magnet mit Reisefoto' }), longDescription: JSON.stringify({ pt: 'Íman acrílico com impressão de foto de viagem e texto personalizado.', fr: 'Aimant acrylique com impression de photo de voyage et texte personnalisé.', en: 'Acrylic magnet with travel photo and personalized text.', de: 'Acrylmagnet mit Reisefoto und personalisiertem Text.' }), priceCents: 1200, stock: 30 },
  { slug: 'travel-souvenir-wooden-map', category: 'travel_souvenirs', name: JSON.stringify({ pt: 'Mapa em Madeira 3D', fr: 'Carte 3D en Bois', en: '3D Wooden Map', de: '3D Holzkarte' }), shortDescription: JSON.stringify({ pt: 'Mapa 3D gravado de destino', fr: 'Carte 3D gravée de destination', en: 'Engraved 3D destination map', de: 'Gravierte 3D-Zielkarte' }), longDescription: JSON.stringify({ pt: 'Mapa em madeira gravado em 3D com o nome do destino de viagem.', fr: 'Carte en bois gravée em 3D com le nom de la destination de voyage.', en: 'Wooden map laser-engraved in 3D with travel destination name.', de: 'Holzkarte laser-graviert in 3D mit Reisezielname.' }), priceCents: 3500, stock: 8 },
  { slug: 'travel-souvenir-keychain-destination', category: 'travel_souvenirs', name: JSON.stringify({ pt: 'Chaveiro de Destino', fr: 'Porte-clés Destination', en: 'Destination Keychain', de: 'Zielort-Schlüsselanhänger' }), shortDescription: JSON.stringify({ pt: 'Chaveiro com gravação de local', fr: 'Porte-clés com gravure du lieu', en: 'Keychain with location engraving', de: 'Schlüsselanhänger mit Ortsgraur' }), longDescription: JSON.stringify({ pt: 'Chaveiro de metal com gravação laser do nome de destino de viagem.', fr: 'Porte-clés en métal com gravure laser du nom de destination de voyage.', en: 'Metal keychain with laser-engraved travel destination name.', de: 'Metallschlüsselanhänger mit Laser-Zielortgravur.' }), priceCents: 1500, stock: 25 },
  { slug: 'travel-souvenir-journal-custom', category: 'travel_souvenirs', name: JSON.stringify({ pt: 'Diário de Viagem', fr: 'Journal de Voyage', en: 'Travel Journal', de: 'Reisetagebuch' }), shortDescription: JSON.stringify({ pt: 'Caderno com capa personalizada', fr: 'Carnet com couverture personnalisée', en: 'Notebook with custom cover', de: 'Notizbuch mit benutzerdefiniertem Cover' }), longDescription: JSON.stringify({ pt: 'Diário de viagem com capa gravada e nome de destino personalizado.', fr: 'Journal de voyage com couverture gravée et nom de destination personnalisé.', en: 'Travel journal with engraved cover and personalized destination name.', de: 'Reisetagebuch mit graviertem Cover und personalisiertem Zielname.' }), priceCents: 2800, stock: 10 },
  { slug: 'travel-souvenir-coaster-set', category: 'travel_souvenirs', name: JSON.stringify({ pt: 'Kit de Suportes de Copos', fr: 'Kit de Sous-verres', en: 'Coaster Set', de: 'Untersetzer-Set' }), shortDescription: JSON.stringify({ pt: 'Suportes com imagens de destinos', fr: 'Sous-verres com images de destinations', en: 'Coasters with destination images', de: 'Untersetzer mit Zielortbildern' }), longDescription: JSON.stringify({ pt: 'Kit com 4 suportes de cortiça com imagens de locais turísticos.', fr: 'Kit com 4 sous-verres em liège com images de lieux touristiques.', en: 'Set of 4 cork coasters with images of tourist destinations.', de: 'Satz von 4 Korkuntersetzern mit Bildern von Touristenzielen.' }), priceCents: 2500, stock: 14 },
  { slug: 'travel-souvenir-tshirt-destination', category: 'travel_souvenirs', name: JSON.stringify({ pt: 'T-Shirt de Viagem', fr: 'T-Shirt de Voyage', en: 'Travel T-Shirt', de: 'Reise-T-Shirt' }), shortDescription: JSON.stringify({ pt: 'T-shirt com mapa e destino', fr: 'T-shirt com carte et destination', en: 'T-shirt with map and destination', de: 'T-Shirt mit Karte und Ziel' }), longDescription: JSON.stringify({ pt: 'T-shirt 100% algodão com impressão de mapa e nome de destino.', fr: 'T-shirt 100% coton com impression de carte et nom de destination.', en: '100% cotton t-shirt with map and destination name printed.', de: '100% Baumwoll-T-Shirt mit gedruckter Karte und Zielname.' }), priceCents: 1800, stock: 18 },
  { slug: 'travel-souvenir-photo-book', category: 'travel_souvenirs', name: JSON.stringify({ pt: 'Álbum de Fotos', fr: 'Album Photo', en: 'Photo Album', de: 'Fotoalbum' }), shortDescription: JSON.stringify({ pt: 'Álbum com capa personalizada', fr: 'Album com couverture personnalisée', en: 'Album with custom cover', de: 'Album mit benutzerdefiniertem Cover' }), longDescription: JSON.stringify({ pt: 'Álbum de fotos com capa gravada e nome de viagem personalizado.', fr: 'Album de photos com couverture gravée et nom de voyage personnalisé.', en: 'Photo album with engraved cover and personalized travel name.', de: 'Fotoalbum mit graviertem Cover und personalisiertem Reisename.' }), priceCents: 3200, stock: 9 },
  { slug: 'travel-souvenir-coffee-mug', category: 'travel_souvenirs', name: JSON.stringify({ pt: 'Caneca de Viagem', fr: 'Mug de Voyage', en: 'Travel Mug', de: 'Reisebecher' }), shortDescription: JSON.stringify({ pt: 'Caneca com imagem de destino', fr: 'Mug com image de destination', en: 'Mug with destination image', de: 'Becher mit Zielortbild' }), longDescription: JSON.stringify({ pt: 'Caneca de cerâmica com impressão UV de imagem turística.', fr: 'Mug em céramique com impression UV d\'image touristique.', en: 'Ceramic mug with UV printing of tourist destination image.', de: 'Keramikbecher mit UV-Druck des Touristenzielbildes.' }), priceCents: 1600, stock: 20, featured: true },
  { slug: 'kadoa-product-branded-box', category: 'kadoa_products', name: JSON.stringify({ pt: 'Caixa Branded Kadoa', fr: 'Boîte Kadoa Branded', en: 'Kadoa Branded Box', de: 'Kadoa Branded-Box' }), shortDescription: JSON.stringify({ pt: 'Caixa com logo Kadoa', fr: 'Boîte com logo Kadoa', en: 'Box with Kadoa logo', de: 'Box mit Kadoa-Logo' }), longDescription: JSON.stringify({ pt: 'Caixa MDF premium com gravação laser do logo Kadoa.', fr: 'Boîte MDF premium com gravure laser du logo Kadoa.', en: 'Premium MDF box with laser-engraved Kadoa logo.', de: 'Premium MDF-Box mit Laser-graviertem Kadoa-Logo.' }), priceCents: 3800, stock: 15, featured: true },
  { slug: 'kadoa-product-branded-mug', category: 'kadoa_products', name: JSON.stringify({ pt: 'Caneca Branded Kadoa', fr: 'Mug Kadoa Branded', en: 'Kadoa Branded Mug', de: 'Kadoa Branded-Tasse' }), shortDescription: JSON.stringify({ pt: 'Caneca com logo e tagline', fr: 'Mug com logo et slogan', en: 'Mug with logo and tagline', de: 'Tasse mit Logo und Slogan' }), longDescription: JSON.stringify({ pt: 'Caneca de cerâmica com impressão UV do logo e tagline Kadoa.', fr: 'Mug em céramique com impression UV do logo e slogan Kadoa.', en: 'Ceramic mug with UV printing of Kadoa logo and tagline.', de: 'Keramiktasse mit UV-Druck von Kadoa-Logo und Slogan.' }), priceCents: 1600, stock: 25 },
  { slug: 'kadoa-product-tshirt-brand', category: 'kadoa_products', name: JSON.stringify({ pt: 'T-Shirt Kadoa', fr: 'T-Shirt Kadoa', en: 'Kadoa T-Shirt', de: 'Kadoa T-Shirt' }), shortDescription: JSON.stringify({ pt: 'T-shirt com design exclusivo', fr: 'T-shirt com design exclusivo', en: 'T-shirt with exclusive design', de: 'T-Shirt mit exklusivem Design' }), longDescription: JSON.stringify({ pt: 'T-shirt 100% algodão com impressão exclusiva do design Kadoa.', fr: 'T-shirt 100% coton com impression exclusive do design Kadoa.', en: '100% cotton t-shirt with exclusive Kadoa design printed.', de: '100% Baumwoll-T-Shirt mit exklusivem Kadoa-Design bedruckt.' }), priceCents: 1800, stock: 20 },
  { slug: 'kadoa-product-sticker-pack', category: 'kadoa_products', name: JSON.stringify({ pt: 'Pack de Adesivos Kadoa', fr: 'Pack Autocollants Kadoa', en: 'Kadoa Sticker Pack', de: 'Kadoa Aufkleberset' }), shortDescription: JSON.stringify({ pt: 'Conjunto de adesivos com designs', fr: 'Ensemble d\'autocollants com designs', en: 'Set of stickers with designs', de: 'Satz von Aufklebern mit Designs' }), longDescription: JSON.stringify({ pt: 'Pack com 12 adesivos variados com designs exclusivos Kadoa.', fr: 'Pack com 12 autocollants variés com designs exclusifs Kadoa.', en: 'Pack of 12 varied stickers with exclusive Kadoa designs.', de: 'Satz von 12 verschiedenen Aufklebern mit exklusiven Kadoa-Designs.' }), priceCents: 1200, stock: 40 },
  { slug: 'kadoa-product-branded-pen', category: 'kadoa_products', name: JSON.stringify({ pt: 'Caneta Branded Kadoa', fr: 'Stylo Kadoa Branded', en: 'Kadoa Branded Pen', de: 'Kadoa Branded-Stift' }), shortDescription: JSON.stringify({ pt: 'Caneta premium com logo', fr: 'Stylo premium com logo', en: 'Premium pen with logo', de: 'Premium-Stift mit Logo' }), longDescription: JSON.stringify({ pt: 'Caneta premium com gravação do logo Kadoa e tinta de qualidade.', fr: 'Stylo premium com gravure do logo Kadoa e tinta de qualidade.', en: 'Premium pen with Kadoa logo engraving and quality ink.', de: 'Premium-Stift mit Kadoa-Logo-Gravur und hochwertiger Tinte.' }), priceCents: 1500, stock: 50 },
  { slug: 'kadoa-product-notebook', category: 'kadoa_products', name: JSON.stringify({ pt: 'Caderno Kadoa', fr: 'Cahier Kadoa', en: 'Kadoa Notebook', de: 'Kadoa Notizbuch' }), shortDescription: JSON.stringify({ pt: 'Caderno com capa exclusiva', fr: 'Cahier com couverture exclusive', en: 'Notebook with exclusive cover', de: 'Notizbuch mit exklusivem Cover' }), longDescription: JSON.stringify({ pt: 'Caderno com capa gravada em madeira com logo Kadoa.', fr: 'Cahier com couverture gravée em bois com logo Kadoa.', en: 'Notebook with wooden cover engraved with Kadoa logo.', de: 'Notizbuch mit Holzcover graviert mit Kadoa-Logo.' }), priceCents: 2200, stock: 18 },
  { slug: 'kadoa-product-keychain', category: 'kadoa_products', name: JSON.stringify({ pt: 'Chaveiro Kadoa', fr: 'Porte-clés Kadoa', en: 'Kadoa Keychain', de: 'Kadoa Schlüsselanhänger' }), shortDescription: JSON.stringify({ pt: 'Chaveiro premium com logo', fr: 'Porte-clés premium com logo', en: 'Premium keychain with logo', de: 'Premium-Schlüsselanhänger mit Logo' }), longDescription: JSON.stringify({ pt: 'Chaveiro de metal premium com gravação do logo Kadoa.', fr: 'Porte-clés em métal premium com gravure do logo Kadoa.', en: 'Premium metal keychain with Kadoa logo engraving.', de: 'Premium-Metallschlüsselanhänger mit Kadoa-Logo-Gravur.' }), priceCents: 1400, stock: 35 },
  { slug: 'kadoa-product-branded-hat', category: 'kadoa_products', name: JSON.stringify({ pt: 'Boné Kadoa', fr: 'Casquette Kadoa', en: 'Kadoa Cap', de: 'Kadoa Kappe' }), shortDescription: JSON.stringify({ pt: 'Boné com bordado do logo', fr: 'Casquette com broderie do logo', en: 'Cap with embroidered logo', de: 'Kappe mit gesticktem Logo' }), longDescription: JSON.stringify({ pt: 'Boné de qualidade com bordado do logo Kadoa na frente.', fr: 'Casquette de qualidade com broderie do logo Kadoa em avant.', en: 'Quality cap with Kadoa logo embroidered on front.', de: 'Qualitäts-Kappe mit gestickertem Kadoa-Logo vorne.' }), priceCents: 1900, stock: 22 },
  { slug: 'kadoa-product-eco-bag', category: 'kadoa_products', name: JSON.stringify({ pt: 'Bolsa Eco Kadoa', fr: 'Sac Éco Kadoa', en: 'Kadoa Eco Bag', de: 'Kadoa Öko-Tasche' }), shortDescription: JSON.stringify({ pt: 'Bolsa sustentável com logo', fr: 'Sac durable com logo', en: 'Sustainable bag with logo', de: 'Nachhaltige Tasche mit Logo' }), longDescription: JSON.stringify({ pt: 'Bolsa de algodão orgânico com impressão do logo Kadoa.', fr: 'Sac em coton biologique com impressão do logo Kadoa.', en: 'Organic cotton bag with Kadoa logo printing.', de: 'Tasche aus Bio-Baumwolle mit Kadoa-Logo-Druck.' }), priceCents: 2100, stock: 28, featured: true },
  { slug: 'custom-product-photo-pillow', category: 'customizable_products', name: JSON.stringify({ pt: 'Almofada com Foto', fr: 'Coussin avec Photo', en: 'Photo Pillow', de: 'Fotokissen' }), shortDescription: JSON.stringify({ pt: 'Almofada com foto personalizada', fr: 'Coussin com photo personnalisée', en: 'Pillow with custom photo', de: 'Kissen mit benutzerdefiniertem Foto' }), longDescription: JSON.stringify({ pt: 'Almofada de qualidade com sublimação de foto personalizada.', fr: 'Coussin de qualité com sublimation de photo personnalisée.', en: 'Quality pillow with personalized photo sublimation.', de: 'Qualitätskissen mit personalisierter Foto-Sublimation.' }), priceCents: 2800, stock: 12, featured: true },
  { slug: 'custom-product-photo-blanket', category: 'customizable_products', name: JSON.stringify({ pt: 'Cobertor com Foto', fr: 'Couverture Photo', en: 'Photo Blanket', de: 'Fotowurf' }), shortDescription: JSON.stringify({ pt: 'Cobertor com foto personalizada', fr: 'Couverture com photo personnalisée', en: 'Blanket with custom photo', de: 'Wurf mit benutzerdefiniertem Foto' }), longDescription: JSON.stringify({ pt: 'Cobertor macio com impressão de foto personalizada em alta qualidade.', fr: 'Couverture doce com impressão de photo personnalisée em haute qualité.', en: 'Soft blanket with high-quality custom photo printing.', de: 'Weiches Tuch mit hochwertigem benutzerdefiniertem Fotodruck.' }), priceCents: 3500, stock: 8 },
  { slug: 'custom-product-phone-case', category: 'customizable_products', name: JSON.stringify({ pt: 'Capa de Telemóvel', fr: 'Étui Téléphone', en: 'Phone Case', de: 'Handyhülle' }), shortDescription: JSON.stringify({ pt: 'Capa personalizada com design', fr: 'Étui personnalisé com design', en: 'Case with custom design', de: 'Hülle mit benutzerdefiniertem Design' }), longDescription: JSON.stringify({ pt: 'Capa de telemóvel com impressão personalizada de design e fotos.', fr: 'Étui téléphone com impressão personnalisée de design et photos.', en: 'Phone case with personalized design and photo printing.', de: 'Handyhülle mit personalisiertem Design- und Fotodruck.' }), priceCents: 1800, stock: 25 },
  { slug: 'custom-product-puzzle', category: 'customizable_products', name: JSON.stringify({ pt: 'Puzzle Personalizado', fr: 'Puzzle Personnalisé', en: 'Custom Puzzle', de: 'Benutzerdefiniertes Puzzle' }), shortDescription: JSON.stringify({ pt: 'Puzzle com foto própria', fr: 'Puzzle com votre photo', en: 'Puzzle with your photo', de: 'Puzzle mit Ihrem Foto' }), longDescription: JSON.stringify({ pt: 'Puzzle de qualidade com 500 peças de sua foto favorita.', fr: 'Puzzle de qualité com 500 pièces de votre photo préférée.', en: 'Quality 500-piece puzzle made from your favorite photo.', de: 'Qualitäts-500-teiliges Puzzle aus Ihrem Lieblingsfoto.' }), priceCents: 2500, stock: 10 },
  { slug: 'custom-product-canvas-print', category: 'customizable_products', name: JSON.stringify({ pt: 'Quadro em Tela', fr: 'Toile Imprimée', en: 'Canvas Print', de: 'Leinwanddruck' }), shortDescription: JSON.stringify({ pt: 'Quadro com foto em tela', fr: 'Toile com votre foto', en: 'Canvas with your photo', de: 'Leinwand mit Ihrem Foto' }), longDescription: JSON.stringify({ pt: 'Quadro em tela de qualidade com impressão de sua foto.', fr: 'Toile de qualité com impressão de votre foto.', en: 'Quality canvas print of your photo for wall display.', de: 'Hochwertiger Leinwanddruck Ihres Fotos für die Wandanzeige.' }), priceCents: 4200, stock: 6 },
  { slug: 'custom-product-mousepad', category: 'customizable_products', name: JSON.stringify({ pt: 'Tapete de Rato', fr: 'Tapis de Souris', en: 'Mouse Pad', de: 'Mauspad' }), shortDescription: JSON.stringify({ pt: 'Tapete com design personalizado', fr: 'Tapis com design personnalisé', en: 'Pad with custom design', de: 'Mauspad mit benutzerdefiniertem Design' }), longDescription: JSON.stringify({ pt: 'Tapete de rato com borracha antiderrapante e design personalizado.', fr: 'Tapis de souris com borracha antidérrapante e design personnalisé.', en: 'Mouse pad with non-slip rubber and personalized design.', de: 'Mauspad mit rutschfester Gummirückseite und personalisiertem Design.' }), priceCents: 1500, stock: 30 },
  { slug: 'custom-product-water-bottle', category: 'customizable_products', name: JSON.stringify({ pt: 'Garrafa Personalizada', fr: 'Bouteille Personnalisée', en: 'Custom Water Bottle', de: 'Benutzerdefinierte Wasserflasche' }), shortDescription: JSON.stringify({ pt: 'Garrafa com design próprio', fr: 'Bouteille com votre design', en: 'Bottle with your design', de: 'Flasche mit Ihrem Design' }), longDescription: JSON.stringify({ pt: 'Garrafa térmica personalizada com sublimação de design.', fr: 'Bouteille thermique personnalisée com sublimation de design.', en: 'Personalized thermal bottle with sublimated design.', de: 'Personalisierte Thermoflasche mit sublimiertem Design.' }), priceCents: 2200, stock: 18 },
  { slug: 'custom-product-apron-kitchen', category: 'customizable_products', name: JSON.stringify({ pt: 'Avental de Cozinha', fr: 'Tablier de Cuisine', en: 'Kitchen Apron', de: 'Kochschürze' }), shortDescription: JSON.stringify({ pt: 'Avental com design personalizado', fr: 'Tablier com design personnalisé', en: 'Apron with custom design', de: 'Schürze mit benutzerdefiniertem Design' }), longDescription: JSON.stringify({ pt: 'Avental de cozinha resistente com impressão personalizada.', fr: 'Tablier de cuisine résistant com impression personnalisée.', en: 'Durable kitchen apron with personalized printing.', de: 'Strapazierfähige Kochschürze mit personalisiertem Druck.' }), priceCents: 1700, stock: 22 },
  { slug: 'custom-product-photo-book', category: 'customizable_products', name: JSON.stringify({ pt: 'Livro de Fotos', fr: 'Livre Photo', en: 'Photo Book', de: 'Fotobuch' }), shortDescription: JSON.stringify({ pt: 'Livro com suas fotos', fr: 'Livre com vos photos', en: 'Book with your photos', de: 'Buch mit Ihren Fotos' }), longDescription: JSON.stringify({ pt: 'Livro de fotos profissional com encadernação de qualidade.', fr: 'Livre de photos professionnel com reliure de qualidade.', en: 'Professional photo book with quality binding.', de: 'Professionelles Fotobuch mit hochwertiger Bindung.' }), priceCents: 5500, stock: 4, featured: true },
];

async function main() {
  console.log('🌱 Iniciando seed de produtos...');

  await prisma.product.deleteMany({});
  console.log('✅ Produtos existentes removidos');

  let count = 0;
  for (const product of products) {
    await prisma.product.create({ data: product });
    count++;
  }

  console.log(`\n🎉 Seed completo! ${count} produtos criados.`);
}

main()
  .then(() => prisma.$disconnect())
  .catch(async (e) => {
    console.error('❌ Erro:', e);
    await prisma.$disconnect();
    process.exit(1);
  });
